### PR TITLE
Update README with conda/mamba install

### PR DESCRIPTION
**Pull request by bjlittle**
This pull-request updates the `README.rst` with simple instructions to the user community on how to install `pytest-pyvista` using `conda` or `mamba` from the newly hatched package on [conda-forge](https://anaconda.org/conda-forge/pytest-pyvista).

### CODE REVIEW

**Review by MatthewFlamm — APPROVED** [review]
LGTM.

**Review by tkoyama010 — APPROVED** [review]

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
We can also add badge is'nt it?

**Comment by tkoyama010** [comment]
Add it to this PR, please.  I will review it. Thanks!

**Comment by bjlittle** [comment]
@tkoyama010 and @MatthewFlamm 

The badges now look like this ...
image

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
