### PR TITLE
Fix reset_image_cache

### LINKED ISSUE #38: reset_image_cache is not working
The flag is doing nothing for me locally

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #38

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
Added a test

**Review by MatthewFlamm — APPROVED** [review]
LGTM

**Comment by MatthewFlamm** [comment]
#36 will needs to consider this flag too.  But we need to get the base functionality working before tackling the corner cases.

**Comment by banesullivan** [comment]
Thanks for adding tests!

**Pull request merged**
